
smtp.host:
smtp.port: 587

from.email:
to.email:
reply.email:
email.subject:
email.message:

# Default logging configuration
logging.level.: WARN
logging.level.org.springframework: INFO
logging.level.com.locusintellect: INFO
